# Generated by Django 4.2.2 on 2023-06-19 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_wallet", "0002_btcmodel_user_alter_btcmodel_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="btcmodel",
            name="address",
        ),
        migrations.RemoveField(
            model_name="btcmodel",
            name="created",
        ),
        migrations.RemoveField(
            model_name="btcmodel",
            name="private_key",
        ),
        migrations.RemoveField(
            model_name="btcmodel",
            name="public_key",
        ),
        migrations.RemoveField(
            model_name="btcmodel",
            name="user",
        ),
        migrations.RemoveField(
            model_name="ethmodel",
            name="address",
        ),
        migrations.RemoveField(
            model_name="ethmodel",
            name="created",
        ),
        migrations.RemoveField(
            model_name="ethmodel",
            name="private_key",
        ),
        migrations.RemoveField(
            model_name="ethmodel",
            name="public_key",
        ),
    ]
