# Generated by Django 4.2.2 on 2023-07-08 16:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core_wallet", "0004_btcmodel_user_ethmodel_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BtcModel",
            new_name="UsdModel",
        ),
    ]
