# Generated by Django 4.2.2 on 2023-07-17 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core_wallet", "0005_rename_btcmodel_usdmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="ethmodel",
            name="wallet_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ethmodel",
            name="wallet_id",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.CreateModel(
            name="BtcInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_id", models.CharField(blank=True, max_length=250, null=True)),
                ("address", models.CharField(blank=True, max_length=250, null=True)),
                ("btcvalue", models.IntegerField(blank=True, null=True)),
                ("received", models.IntegerField(blank=True, null=True)),
                ("txid", models.CharField(blank=True, max_length=250, null=True)),
                ("rbf", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "btc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core_wallet.usdmodel",
                    ),
                ),
            ],
        ),
    ]
