# Generated by Django 4.2.2 on 2023-07-25 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_wallet", "0006_ethmodel_wallet_address_ethmodel_wallet_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usdmodel",
            name="wallet_address",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
