# Generated by Django 4.2.2 on 2023-06-24 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("email_msg_generator", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OpenAiModel",
            new_name="OpenAiAdminModel",
        ),
        migrations.CreateModel(
            name="OpenAiUserModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("custom_user_key_id", models.IntegerField(blank=True, null=True)),
                (
                    "open_ai_key",
                    models.CharField(blank=True, max_length=400, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
