# Generated by Django 4.2.2 on 2023-06-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "email_msg_generator",
            "0002_rename_openaimodel_openaiadminmodel_openaiusermodel",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="openaiadminmodel",
            name="assigned",
            field=models.BooleanField(default=False),
        ),
    ]
