# Generated by Django 4.2.2 on 2023-06-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_msg_generator", "0003_openaiadminmodel_assigned"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailGenerator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField(max_length=1000000)),
                ("generated_message", models.FileField(upload_to="messages")),
            ],
        ),
        migrations.CreateModel(
            name="EmailPromptMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
