# Generated by Django 4.2.2 on 2023-06-27 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("email_msg_generator", "0004_emailgenerator_emailpromptmessage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailPromptMessage",
        ),
    ]
