# Generated by Django 4.2.2 on 2023-06-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_msg_generator", "0005_delete_emailpromptmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailGeneratorModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numbe_of_mail", models.IntegerField()),
                ("prompt", models.TextField(max_length=1000000)),
                ("generated_emails", models.FileField(upload_to="messages")),
            ],
        ),
        migrations.DeleteModel(
            name="EmailGenerator",
        ),
    ]
