# Generated by Django 4.2.2 on 2023-06-27 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("email_msg_generator", "0007_emailgeneratormodel_swapped_emails_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emailgeneratormodel",
            old_name="numbe_of_mail",
            new_name="number_of_mail",
        ),
    ]
