# Generated by Django 4.2.2 on 2023-06-28 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "email_msg_generator",
            "0008_rename_numbe_of_mail_emailgeneratormodel_number_of_mail",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_stored", models.CharField(max_length=1000)),
                ("request_id", models.TextField(max_length=4000)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
