# Generated by Django 4.2.2 on 2023-07-16 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_msg_generator", "0010_openaiusermodel_time_of_assigning"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openaiusermodel",
            name="time_of_assigning",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 16, 11, 20, 33, 780401, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
