# Generated by Django 4.2.2 on 2023-07-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_msg_generator", "0011_alter_openaiusermodel_time_of_assigning"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openaiusermodel",
            name="time_of_assigning",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
