# Generated by Django 4.2.2 on 2023-07-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_msg_generator", "0012_alter_openaiusermodel_time_of_assigning"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailMessageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=400)),
                ("message_body", models.TextField()),
                ("site_url", models.CharField(max_length=400)),
            ],
        ),
    ]
