# Generated by Django 4.2.2 on 2023-07-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_msg_generator", "0014_emailmessagemodel_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailmessagemodel",
            name="maillist",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emailmessagemodel",
            name="message_body",
            field=models.TextField(blank=True, null=True),
        ),
    ]
