# Generated by Django 4.2.2 on 2023-07-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_msg_generator", "0015_emailmessagemodel_maillist_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailmessagemodel",
            name="maillist",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
