# Generated by Django 4.2.2 on 2023-07-25 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("email_msg_generator", "0016_alter_emailmessagemodel_maillist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailmessagemodel",
            name="maillist",
        ),
    ]
