# Generated by Django 4.2.2 on 2023-07-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_msg_generator", "0017_remove_emailmessagemodel_maillist"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailmessagemodel",
            name="maillist",
            field=models.TextField(blank=True, null=True),
        ),
    ]
