# Generated by Django 4.2.3 on 2023-07-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_msg_generator", "0018_emailmessagemodel_maillist"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailgeneratormodel",
            name="access_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
