# Generated by Django 4.2.2 on 2023-06-23 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="open_ai_key",
            field=models.TextField(blank=True, null=True),
        ),
    ]
