# Generated by Django 4.2.2 on 2023-07-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_user", "0006_alter_currentusertoken_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="currentusertoken",
            name="time_of_generation",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
