# Generated by Django 4.2.2 on 2023-07-16 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_user", "0007_currentusertoken_time_of_generation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="open_ai_key",
        ),
    ]
